name: todos_data_source
description: A generic interface for managing todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ">=2.3.3 <3.0.0" 
  json_serializable: ">=6.6.1 <7.0.0"
  mocktail: ">=1.0.3 <2.0.0"
  test: ">=1.19.2 <2.0.0"
  very_good_analysis: ">=5.1.0 <6.0.0"
dependencies:
  equatable: ">=2.0.5 <3.0.0" 
  json_annotation: ">=4.8.0 <5.0.0" 
  meta: ">=1.9.0 <2.0.0"
